### ISSUE TITLE
RFC: Drop python 2.7 compatibility

### ISSUE THREAD

**Issue by ambrosejcarr** [broadinstitute/cromwell-tools#26]
- Python 2.7 compatibility prevents the use of some helpful tools (e.g. `shutil.which` for path checking)
- Python 2.7 is the past

Can we drop support for 2.7 in cromwell-tools?

**Comment by rexwangcc** [comment]
I personally up for dropping the py2.x support. The only problem is since Lira is depending on Cromwell-tools, we have to migrate to py3 at the same time for Lira, Cromwell-tools, and pipeline-tools, maybe also including the test suites in secondary-analysis. A consistent refactoring is required here. 

Should get more people involved in this topic.

**Comment by ambrosejcarr** [comment]
I think I tagged everyone. :)

**Comment by lbergelson** [comment]
👍 to dropping python 2 from the world.

**Comment by notestaff** [comment]
As a user I’m for keeping python2 support.  Some packages eg dxpy for dnanexus require python2, and I want to have one environment with everything.  Also, I work on https://github.com/broadinstitute/viral-ngs and want to use cromwell-tools as a dependency, but we’re trying to keep python2 compatibility for viral-ngs .

**Comment by rexwangcc** [comment]
Given the great feedback and discussion from this issue, in the most recent refactor PR, we decided to keep support for both Py2 and Py3 (2.7/3.5+), and we have set up the Travis CI to run unit tests in both envs to ensure the backward compatibility.

In the long-term, we will keep support both Py2 and Py3 until it's not worthy to do it(e.g. most of the major packages we use here drop Py2 support)

So I think we could close this RFC with https://github.com/broadinstitute/cromwell-tools/pull/43
