### ISSUE TITLE
TypeError: harmonize_credentials() got an unexpected keyword argument 'caas_key'

### ISSUE THREAD

**Issue by TMiguelT** [broadinstitute/cromwell-tools#51]
I get the error `TypeError: harmonize_credentials() got an unexpected keyword argument 'caas_key'` when I attempt to run cromwell-tools on Python 3.6:

```bash
$ cromwell-tools status --uuid 305cafa1-111c-4ad1-bbae-a4a63c33a018 --url localhost:8000
Traceback (most recent call last):
  File "/usr/local/bin/cromwell-tools", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/cromwell_tools/cli.py", line 108, in main
    command, args = parser(arguments)
  File "/usr/local/lib/python3.6/dist-packages/cromwell_tools/cli.py", line 96, in parser
    auth = CromwellAuth.harmonize_credentials(**auth_arg_dict)
TypeError: harmonize_credentials() got an unexpected keyword argument 'caas_key'
```

**Comment by danxmoran** [comment]
Missed a spot on the renaming in #50, should be an easy fix.

**Comment by rexwangcc** [comment]
@TMiguelT Thanks for submitting the issue! We have an open PR to fix this issue, in the meantime, since this issue is located in the CLI command parser itself, you could still try to play with the lib in python console/Jupyter Notebook by following the [Quickstart example](https://github.com/broadinstitute/cromwell-tools/blob/master/notebooks/Quickstart/quickstart.ipynb)
